create database  capstone;
use capstone;
select*from capstone.brands;
select * from capstone.orderss;
select*from capstone.order_items;
select* from capstone.products;
select*from capstone.stores;
select * from capstone.stocks;
select*from capstone.staffs;
select*from capstone.categories;
select*from customer_segments;


alter table capstone.order_items change `Total Price` total_price double;
alter table capstone.order_items change `product name` product_name varchar(100);
select count(*) from capstone.orderss;
select count(*) from capstone.order_items;
select count(*) from capstone.products;

-- 3. InnerJoin for Order Details
-- Join orders, order_items, and products to display detailed line items.
select o.order_id,p.product_name,oi.quantity,oi.discount,oi.total_price
 from capstone.orderss o
inner join capstone.order_items oi
on o.order_id=oi.order_id
inner join capstone.products p 
on oi.product_id=p.product_id;

-- 4. Total Sales by Store
-- Write a query to group sales (total_price) by each store_id.
select st.store_name,sum(oi.total_price) as TP
from capstone.order_items oi
inner join capstone.orderss o
on o.order_id=oi.order_id
inner join capstone.stores st
on o.order_id=st.store_id
group by st.store_name;

-- 5.Top 5 Selling Products
-- Use ORDER BY and LIMIT to get the top 5 most sold products by quantity
select product_name,quantity from order_items
order by quantity desc limit 5;

-- 6. Customer Purchase Summary
-- For each customer, return total orders placed, total items purchased,and total revenue.
select c.customer_id, c.first_name,c.last_name,
count(o.order_id) as tot_ord_plc,sum(oi.quantity) as tot_item_purch,sum(oi.total_price) as total_revenue 
from customers c
join orderss o
on c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.customer_id
order by total_revenue;

-- 7.Segment Customers by Total Spend
-- Write a query to classify customers into spending brackets (e.g., low,medium, high).
select max(total_price),product_name from capstone.order_items group by product_name;
select *,
case
when total_price>1000 then "high budget"
when total_price>500 then "medium buget"
when total_price<500 then "low budget"
else "very low budget "
end as spendings
from capstone.order_items;

-- 8. Staff Performance Analysis
-- Analyze total revenue generated by each staff member based on their handled orders.
select sum(oi.total_price) as revenue_generate,st.staff_id,st.first_name from order_items oi
inner join orderss o
on oi.order_id=o.order_id
inner join staffs st 
on o.staff_id=st.staff_id
group by st.staff_id;

-- 9. Stock Alert Query
-- Write a query to list products where stock quantity < 10 in any store.
select p.product_id, p.product_name,sto.quantity from capstone.products p
inner join capstone.stocks sto
on p.product_id=sto.product_id
where sto.quantity<10;
-- 10. Create Final Segmentation Table
-- Create a table customer_segments that will be populated from Python ML results later.


